#!/bin/bash
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    if [ -x "$(command -v supervisord-foreground)" ]; then
        set -- supervisord-foreground "$@"
    elif [ -x "$(command -v httpd-foreground)" ]; then
        set -- httpd-foreground "$@"
    elif [ -x "$(command -v php-fpm)" ]; then
        set -- php-fpm "$@"
    else
        set -- php "$@"
    fi
fi

echo "[ ****************** ] Starting Endpoint of Application"
if [ -f "/app/init" ];then
	/app/init --env=${APP_ENV:-Production} --overwrite=y
fi

if [ -f "/app/yii" ];then
	/app/yii migrate/up --interactive=0
fi

echo "[ ****************** ] Ending Endpoint of Application"

exec "$@"

