#!/bin/bash
set -euo pipefail

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    if [ -x "$(command -v supervisord-foreground)" ]; then
        set -- supervisord-foreground "$@"
    elif [ -x "$(command -v httpd-foreground)" ]; then
        set -- httpd-foreground "$@"
    elif [ -x "$(command -v php-fpm)" ]; then
        set -- php-fpm "$@"
    else
        set -- php "$@"
    fi
fi

if [ -f "/app/yii" ];then
	echo "[ ****************** ] Starting Endpoint of Application"
	php yii migrate/up --interactive=0

	echo "[ ****************** ] Ending Endpoint of Application"
fi

exec "$@"

