#!/bin/bash
set -e -x

echo "Initialize the application."

if [ -f "/app/init" ];then
	/app/init --env=${APP_ENV:-Production} --overwrite=y
	ln -s /app/http.nginx /usr/local/etc/nginx/sites/nginx.conf
fi

if [ -f "/app/yii" ];then
	/app/yii migrate/up --interactive=0
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    if [ -x "$(command -v supervisord-foreground)" ]; then
        set -- supervisord-foreground "$@"
    elif [ -x "$(command -v httpd-foreground)" ]; then
        set -- httpd-foreground "$@"
    elif [ -x "$(command -v php-fpm)" ]; then
        set -- php-fpm "$@"
    else
        set -- php "$@"
    fi
fi

exec "$@"

