FROM xutl/php:5.6-cli-centos7

MAINTAINER XUTONGLE <xutongle@gmail.com>

# Environment settings
ENV PATH=/app:/app/vendor/bin:/root/.composer/vendor/bin:$PATH \
    TERM=linux \
    COMPOSER_ALLOW_SUPERUSER=1

VOLUME ["/root/.composer"]
