FROM xutl/php:7.2-fpm-xenial

MAINTAINER XUTONGLE <xutongle@gmail.com>

# Environment settings
ENV PATH=/app:/app/vendor/bin:/root/.composer/vendor/bin:$PATH \
    TERM=linux \
    COMPOSER_ALLOW_SUPERUSER=1

VOLUME ["/root/.composer"]